spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      mysms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        method: POST
        appcode: 9448945d840d4a6493c905c145fb0a83
        sms-signId: 2e65b1bb3d054466b82f0c9d125465e2
        templateId: 908e94ccf08b4476ba6c876d13f084ad
  #      alicloud:
#      access-key: LTAl4FwfjSycd1APnuG9bjj
#      secret-key: O6xaxyiWfSlitcOkSuK27ju4hXT5HI
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#        bucket: gulimall-anonymous

  application:
    name: gulimall-third-party

server:
  port: 30000
